import tkinter as tk
root=tk.Tk()
label1=tk.Label(root,text="Name:")
entry1=tk.Entry(root,)
label2=tk.Label(root,text="class:")
entry2=tk.Entry(root)
label3=tk.Label(root,text="age:")
entry3=tk.Entry(root)
button=tk.Button(root,text="submit")
label1.pack()
label2.pack()
label3.pack()
button.pack()
root.mainloop()