import tkinter as tk
root=tk.Tk()
label1=tk.Label(root,text="Name:")
entry1=tk.Entry()
label2=tk.Label(root,text="class:")
entry2=tk.Entry()
label3=tk.Label(root,text="age:")
entry3=tk.Entry()
button=tk.Button(root,text="submit")
label1.pack()
entry1.pack()
label2.pack()
entry2.pack()
label3.pack()
entry3.pack()
button.pack()
root.mainloop()